# Generated by Django 3.1.3 on 2021-12-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_title', models.CharField(max_length=256)),
                ('href', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ZagsHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zags_title', models.CharField(max_length=256)),
                ('href', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ZagsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born', models.IntegerField()),
                ('died', models.IntegerField()),
                ('wedd', models.IntegerField()),
                ('divorce', models.IntegerField()),
                ('zagshead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zags', to='population.zagshead')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived', models.IntegerField()),
                ('departed', models.IntegerField()),
                ('gain', models.IntegerField()),
                ('migrationhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='population.migrationhead')),
            ],
        ),
    ]
