# Generated by Django 3.1.3 on 2020-12-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('href', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_my', models.CharField(max_length=30)),
                ('period_mmy', models.CharField(max_length=50)),
                ('pre_month', models.CharField(max_length=30)),
                ('pre_year', models.CharField(max_length=30)),
                ('pre_period', models.CharField(max_length=30)),
                ('middle', models.CharField(max_length=200)),
                ('salarynews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salarynews')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=256)),
                ('current', models.FloatField()),
                ('pre_month', models.FloatField()),
                ('pre_year', models.FloatField()),
                ('period', models.FloatField()),
                ('pre_period', models.FloatField()),
                ('middle', models.FloatField()),
                ('salarynews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salarynews')),
            ],
        ),
    ]
